[git]
# XXX
#author.name = 'CoreOS Bot'
#author.email = 'coreos@lists.fedoraproject.org'
author.name = 'Jonathan Lebon'
author.email = 'jonathan@jlebon.com'
# XXX
#github.repo.owner = 'coreos'
github.repo.owner = 'jlebon'
github.repo.name = 'fedora-coreos-config'
# XXX
#github.username = 'coreosbot'
github.token.username = 'papr-bot'
github.token.path = '/var/run/secrets/coreos.fedoraproject.org/github-token/token'

[sync-build-lockfiles]
builds-base-url = 'https://builds.coreos.fedoraproject.org/prod/streams'
streams = [
    'bodhi-updates',
]
trigger.mode = 'periodic'
# XXX
#trigger.period = '15m'
trigger.period = '15s'
method = 'push'

[promote-lockfiles]
source-ref = 'bodhi-updates'
target-ref = 'testing-devel'
trigger.mode = 'periodic'
# XXX
#trigger.period = '24h'
trigger.period = '15s'
method = 'push'

[propagate-files]
source-ref = 'testing-devel'
target-refs = [
    'bodhi-updates',
]
skip-files = [
    'manifest.yaml',
    'manifest-lock.*',
]
trigger.mode = 'periodic'
# XXX
#trigger.period = '15m'
trigger.period = '15s'
method = 'push'
